const userTypes = {
  USER_DATA_ADDED: 'USER_DATA_ADDED',
  REDUX_DATA_CLEARED: 'REDUX_DATA_CLEARED',
  ADD_TODAY_WORDSBAG: 'ADD_TODAY_WORDSBAG',
  CLEAR_TODAY_WORDSBAG: 'CLEAR_TODAY_WORDSBAG',
};

export default userTypes;
