const userTypes = {
  USER_DATA_ADDED: 'USER_DATA_ADDED',
  REDUX_DATA_CLEARED: 'REDUX_DATA_CLEARED',
  ADD_TODAY_WORDSBAG: 'ADD_TODAY_WORDSBAG',
  CLEAR_TODAY_WORDSBAG: 'CLEAR_TODAY_WORDSBAG',
  UPDATE_CURRENT_WORD: 'UPDATE_CURRENT_WORD',
  MODIFY_DEFAULT_WORDS_BAG: 'MODIFY_DEFAULT_WORDS_BAG',
  ADD_SUBLIST: 'ADD_SUBLIST',
  MODIFY_SUB_LIST: 'MODIFY_SUB_LIST',
};

export default userTypes;
